# Generated by Django 5.0.3 on 2024-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmraTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('meals_per_day', models.IntegerField()),
                ('visa_included', models.BooleanField(default=False)),
                ('medical_assistance', models.BooleanField(default=False)),
                ('experienced_guide', models.CharField(max_length=100)),
                ('zamzam_water_liters', models.IntegerField()),
                ('includes_razor', models.BooleanField(default=False)),
                ('includes_bag', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
